### ISSUE TITLE
harden blackcoin to be post quantum cryptography safe

### ISSUE THREAD

**Issue by xranby** [JohnDolittle/blackcoin-old#69]
BlackCoin key creation is managed by ECDSA, a standard using an elliptic curve algorithm to determine a private/public key pair. ECDSA elliptic curves are _dead_ when quantum computers become/are available because a quantum computer can derive the private key from the public key.

The use of ECDSA elliptic curves is a weakness inherited from BitCoin.

https://en.wikipedia.org/wiki/Elliptic_curve_cryptography#Quantum_computing_attacks

BlackCoin is post quantum cryptography safe as long as you do not re-use addresses. The address hashing function is already post quantum cryptography resistant. However if you spend or _stake_ a BlackCoin then the public key is revealed and that allows an attack to derive the private key using a quantum computer.

BlackCoin need to switch to a post quantum cryptographic safe algorithm for all keys.
BlackCoin need a way to support both old and new keys in a transition process.

https://en.wikipedia.org/wiki/Post-quantum_cryptography

**Comment by rat4** [comment]
BlackCoin's consensus is as post quantum cryptography safe as ECDSA.

Cryptography standards such as ECRYPT II tend to say that Bitcoin's
256-bit ECDSA keys are secure until at least 2030-2040.

https://en.bitcoin.it/wiki/Quantum_computing_and_Bitcoin

**Comment by xranby** [comment]
2016 the largest general purpose quantum computer was 10 qbit
2017 IBM is now offering a general purpose 50qbit computer http://www-03.ibm.com/press/us/en/pressrelease/51740.wss

thus it is reasonable to expect that progress may continue to happen in x5 increase each year
in such a scenario we may see
256qbit general purpose quantum computers in 2018 and
1250qbit general purpose quantum computers in 2019
and 6250qbit general purpose quantum computers in 2010

As soon there is a general purpose system with ~1500qbits that can run the Shor's algorithm then we have reached the tipping point. The quantum computers only need to be operation in research for being a practical issue for ECDSA keys.

**Comment by xranby** [comment]
According to oliver at the IBM forum you only need a 800qbit quantum computer to attach ECDSA in polynomial time, this lower the estimate when a quantum computer is available that can attack ECDSA to the year 2019.

"In order to carck bitcoin, one needs to crack ECDSA private keys.

Is this possible to do in polynomial time with a quantum computer? If the hardware allows it: yes, with adiabatic quantum computation.

Cracking 256 bit ECDSA private key in Q++ pseudocode using 800 qubits:

typedef qbit Par[32];
typedef qbit Key[256];

//INPUT
Par const params={1,1,1,1,0,0,0,0,1,1,0,0,1,0,1,1,...};
Key const public={1,0,1,1,0,1,1,1,0,0,1,1,0,0,1,0,...};

//TEMPORAL
Key       result;

//OUTPUT
Key       private;

//ENTRY POINT
hadamard(private);                     //Compute all possible 2^256 possible combinations
Public_Key_Gen(params,private,result); //Generate the public key of all combinations
CNOT(public,result), result=0;         //This is equivalent to result = public
read(private);                         //Output the private key for the input public key

In general all public / private key cryptosystems assume that P≠NP. What means that NP-complete problems cannot be solved performing polynomial time computation. This is truth: In order to solve any NP-complete problem, one needs NP computation. (Non-Polynomial computation). Quantum computers are able to perform Non-Polynomial computation in polynomial time, since they perform exponential computation 2n in polynomial time."

https://quantumexperience.ng.bluemix.net/#/community/question?questionId=7883b0318a956cbbb7809a396d12122e&answerId=105f52d6d0f1393eea29d61d68ce8df9

**Comment by dzimbeck** [comment]
Thats nonsense... "Quantum computers" won't be cracking anything. They won't even exist except in peoples imaginations. Quantum theory is still pseudoscience at best. Nikola Tesla didn't even believe in atomic theory. Regardless, a computer would have to be multitudes of exponential times faster to crack any such things. If anything is a threat to crypto, its cryptoanalysis. To protect keys one needs only to change them periodically.

As you can see this is just sensationalist journalism...
https://www.wired.com/2014/05/quantum-computing/

**Comment by xranby** [comment]
I dont think we should underestimate research done on quantum computers.
The article you refer to from 2014 critizize the general purposeness of the 2000qbit d-wave computer however the articles i liked to from 2017 is refering to IBM's general purpose qbit systems that are implemented on a much higher density compared to the D-Wave and the IBM implementation is designed for general purpose problems such as running the Shor algorithm.

An overview talk on how quantum computers will affect current cryptographic systems was made at Fosdem 2017, you can see the full talk here: The consensus is that elliptic curves are very dead in a post quantum computing world.
https://fosdem.org/2017/schedule/event/quantum/

**Comment by xranby** [comment]
The D-Wave do Computing in adiabatic quantum
approximation.
According to the IBM forum you can reverse private to public keys using only 800 qbits on a machine that can do adiabatic quantum
approximation hence according to the researchers reversing a public key to a private key should be doable in polynomal time on a D-Wave.

**Comment by dzimbeck** [comment]
Well in any case, research is very compartmentalized. However it works under the hood, they surely don't want researchers to understand what they are researching. They should prove it first. Have they done so beyond the shadow of any reasonable doubt? Otherwise its vaporware. Regardless of my opinion on the journalism, computers are sure to become faster indeed. What do you recommend that is better than the cryptography we use now in BLK?

**Comment by xranby** [comment]
"Isogenies of super singular elliptic curves" is one of the top candidates for a quantum resistant successor for ECC according to Jeremy Wohlwend and i thus one of the top candidates as a key replacement for blackcoin:
https://math.mit.edu/~apost/courses/18.204-2016/18.204_Jeremy_Wohlwend_final_paper.pdf

Two implementation of  "isogenies of super singular elliptic curves" is available in liboqs
https://openquantumsafe.org/
https://github.com/open-quantum-safe/liboqs

**Comment by xranby** [comment]
@javad-doliskani implementation of  "Isogenies of super singular elliptic curves" is found at the following src location inside liboqs:
https://github.com/open-quantum-safe/liboqs/tree/master/src/kex_sidh_iqc_ref

Microsoft implementation of "Isogenies of super singular elliptic curves" is found at the following src location inside liboqs:
https://github.com/open-quantum-safe/liboqs/tree/master/src/kex_sidh_cln16

Since Microsoft is known to collect patent fees from projects using Microsoft MIT licensed code I would hands down choose Javad Doliskani's implementation for "Isogenies of super singular elliptic curves" to stay on the safe side and avoid unnecessary software-patent-litigations caused by Microsoft lawyers.

**Comment by JohnDolittle** [comment]
>256qbit general purpose quantum computers in 2018 

Mar 2018: Google reclaims quantum computer crown with 72 qubit processor

It's still too early, so Blacknet will use Ed25519.
